source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.2'
#gem 'sqlite3'
gem 'pg'
gem 'pg_search'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'cancan'
gem 'devise'
gem 'figaro'
gem 'rolify'
gem 'simple_form'
gem 'thin'
gem 'carrierwave'
gem 'kaminari'
# gem 'bootstrap-datepicker-rails'
gem 'bootstrap-datepicker-rails', :require => 'bootstrap-datepicker-rails',
  :git => 'git://github.com/Nerian/bootstrap-datepicker-rails.git'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'quiet_assets'
  gem 'rails_layout'
end
